#!/usr/bin/env bash
# regen-images.sh — regenerate the README images:
#   images/login-web.png, images/panel-web.png, images/panel-metrics-web.png
#     (headless Chrome, sanitized, dark theme, charts under real induced load)
#   images/usage.gif, images/app-start.gif
#     (vhs)
# Does NOT touch images/logo.png, images/app.ico, or the badge SVGs
# (goreport/goversion/release.svg are generated by releaser.go).
#
# Prerequisites: go, node >= 22, google-chrome (or CHROME_BIN=...), jq, and
# vhs (https://github.com/charmbracelet/vhs). No npm install needed — the web
# script talks to Chrome over the DevTools Protocol with node's built-in
# WebSocket.
#
# Usage:  scripts/regen-images.sh
#
# Sanitization contract: no committed image may contain the real hostname,
# username, IP addresses, or API key. The web script scrubs the panel DOM
# before capture and hard-fails if any real value survives (see SANITIZE in
# scripts/web-screenshots.mjs); the tapes pin PS1 to "$ " and only run
# identity-free commands (see the tape headers).
set -euo pipefail
cd "$(dirname "$0")/.."

PORT=8471
DATA_DIR=$(mktemp -d /tmp/nitr-imgs.XXXXXX)
export NITR_BIN="$DATA_DIR/nitr"
export NITR_PORT="$PORT"

go build -o "$NITR_BIN" .

NITR_OPEN_BROWSER_ON_STARTUP=false "$NITR_BIN" server --port "$PORT" --data-dir "$DATA_DIR" &
SRV_PID=$!
# The server ignores SIGTERM — SIGKILL it, and verify it's gone so a leaked
# server can't hold the port and break the next run.
cleanup() {
  kill -9 "$SRV_PID" 2>/dev/null || true
  rm -rf "$DATA_DIR" /tmp/nitr-demo-cookies /tmp/nitr-demo-start /tmp/nitr-demo-cli
}
trap cleanup EXIT

for _ in $(seq 1 30); do
  curl -sf "http://localhost:$PORT/health" >/dev/null && break
  sleep 1
done

node scripts/web-screenshots.mjs
vhs scripts/nitr-usage.tape
vhs scripts/nitr-app-start.tape

echo "Done. Eyeball images/{login-web,panel-web}.png and images/{usage,app-start}.gif before committing."
